# Generated by Django 4.0.6 on 2024-09-29 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='empresa/')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='empresa/')),
                ('logo_blanco', models.ImageField(blank=True, null=True, upload_to='empresa/')),
                ('mision', models.TextField(blank=True, max_length=400, null=True)),
                ('vision', models.TextField(blank=True, max_length=400, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=15, null=True)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('celular', models.CharField(blank=True, max_length=11, null=True)),
                ('correo', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name_plural': '1. Biologicos ',
            },
        ),
    ]
