# Generated by Django 4.0.6 on 2024-10-02 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biologico', '0003_producto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slider',
            old_name='img_slider',
            new_name='imagen',
        ),
        migrations.AddField(
            model_name='slider',
            name='img_der_inf_der',
            field=models.FileField(blank=True, help_text='slider  1600x964', null=True, upload_to='slider/'),
        ),
        migrations.AddField(
            model_name='slider',
            name='img_der_inf_izq',
            field=models.FileField(blank=True, help_text='slider  1600x964', null=True, upload_to='slider/'),
        ),
        migrations.AddField(
            model_name='slider',
            name='img_der_supe_der',
            field=models.FileField(blank=True, help_text='slider  1600x964', null=True, upload_to='slider/'),
        ),
        migrations.AddField(
            model_name='slider',
            name='img_der_supe_izq',
            field=models.FileField(blank=True, help_text='slider  1600x964', null=True, upload_to='slider/'),
        ),
        migrations.AddField(
            model_name='slider',
            name='img_izq_supe',
            field=models.FileField(blank=True, help_text='slider  1600x964', null=True, upload_to='slider/'),
        ),
    ]
