# Generated by Django 4.0.6 on 2024-10-02 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Biologico', '0004_rename_img_slider_slider_imagen_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'verbose_name_plural': '3. Producto '},
        ),
        migrations.AddField(
            model_name='producto',
            name='img_fondo',
            field=models.FileField(blank=True, help_text='slider  1600x964', null=True, upload_to='slider/'),
        ),
        migrations.AddField(
            model_name='producto',
            name='img_foto01',
            field=models.FileField(blank=True, help_text='slider  1600x964', null=True, upload_to='slider/'),
        ),
        migrations.AddField(
            model_name='producto',
            name='img_foto02',
            field=models.FileField(blank=True, help_text='slider  1600x964', null=True, upload_to='slider/'),
        ),
        migrations.CreateModel(
            name='Beneficios_producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('detalle', models.TextField(blank=True, max_length=400, null=True)),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Biologico.producto')),
            ],
            options={
                'verbose_name_plural': '3. Producto ',
            },
        ),
    ]
