# Generated by Django 4.0.6 on 2024-10-03 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biologico', '0006_alter_beneficios_producto_options_producto_derecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marca',
            name='logo_horiz',
            field=models.ImageField(blank=True, null=True, upload_to='empresa/'),
        ),
    ]
