# Generated by Django 4.2.16 on 2024-10-07 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biologico', '0007_marca_logo_horiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='marca',
            name='facebook',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='marca',
            name='instagram',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='marca',
            name='telefono',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='marca',
            name='tiktok',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='marca',
            name='youtube',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
