# Generated by Django 4.2.16 on 2024-10-07 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biologico', '0008_marca_facebook_marca_instagram_marca_telefono_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.FileField(blank=True, help_text='blog  1600x964', null=True, upload_to='blog/')),
                ('titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('detalle', models.TextField(blank=True, max_length=400, null=True)),
                ('autor', models.CharField(blank=True, max_length=400, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': '5. Blog ',
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='color',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
    ]
