# Generated by Django 4.0.6 on 2024-10-08 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biologico', '0010_producto_sub_titulo2'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficios_producto',
            name='colum_izqui',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='img',
            field=models.FileField(blank=True, help_text='slider  1600x964', null=True, upload_to='producto/'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='img_fondo',
            field=models.FileField(blank=True, help_text='producto fondo  ', null=True, upload_to='producto/'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='img_foto01',
            field=models.FileField(blank=True, help_text='producto  571x570', null=True, upload_to='producto/'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='img_foto02',
            field=models.FileField(blank=True, help_text='producto  270x270', null=True, upload_to='producto/'),
        ),
    ]
