# Generated by Django 4.0.6 on 2024-10-08 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biologico', '0011_beneficios_producto_colum_izqui_alter_producto_img_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edit_pag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imag_fondo_slider', models.FileField(blank=True, help_text='fondo slider  1894x718', null=True, upload_to='slider/')),
            ],
            options={
                'verbose_name_plural': '0. Edición de Pág Web]  ',
            },
        ),
    ]
