# Generated by Django 4.0.6 on 2024-10-08 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biologico', '0012_edit_pag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='edit_pag',
            options={'verbose_name_plural': '0. Edición de Pág Web'},
        ),
        migrations.RenameField(
            model_name='slider',
            old_name='img_der_inf_izq',
            new_name='img_der_inf_izq_1',
        ),
        migrations.AddField(
            model_name='slider',
            name='img_der_inf_izq_2',
            field=models.FileField(blank=True, help_text='slider  1600x964', null=True, upload_to='slider/'),
        ),
    ]
