# Generated by Django 4.0.6 on 2024-10-08 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Biologico', '0013_alter_edit_pag_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='img',
            new_name='img_producto',
        ),
    ]
