# Generated by Django 4.0.6 on 2024-10-08 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biologico', '0016_producto_img_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='img_set_producto',
            field=models.FileField(blank=True, help_text='slider  1600x964', null=True, upload_to='producto/'),
        ),
    ]
