# Generated by Django 4.2.16 on 2024-10-08 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biologico', '0017_producto_img_set_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='edit_pag',
            name='imag_fondo_02',
            field=models.FileField(blank=True, help_text='fondo slider  1894x718', null=True, upload_to='slider/'),
        ),
        migrations.AddField(
            model_name='edit_pag',
            name='imag_fondo_03',
            field=models.FileField(blank=True, help_text='fondo slider  1894x718', null=True, upload_to='slider/'),
        ),
        migrations.AddField(
            model_name='edit_pag',
            name='imag_pie',
            field=models.FileField(blank=True, help_text='fondo slider  1894x718', null=True, upload_to='slider/'),
        ),
    ]
