# Generated by Django 4.0.6 on 2024-10-09 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biologico', '0020_edit_pag_imag_fondo_04_alter_edit_pag_imag_fondo_02_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='edit_pag',
            name='imag_fondo_05',
            field=models.FileField(blank=True, help_text='fondo  1894x718', null=True, upload_to='slider/'),
        ),
        migrations.AddField(
            model_name='edit_pag',
            name='imag_fondo_06',
            field=models.FileField(blank=True, help_text='fondo  1894x718', null=True, upload_to='slider/'),
        ),
    ]
