# Generated by Django 4.0.6 on 2024-10-09 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biologico', '0021_edit_pag_imag_fondo_05_edit_pag_imag_fondo_06'),
    ]

    operations = [
        migrations.AddField(
            model_name='edit_pag',
            name='about_sub_titulo1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='edit_pag',
            name='about_sub_titulo2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='edit_pag',
            name='about_titulo1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='edit_pag',
            name='img_mision',
            field=models.FileField(blank=True, help_text='fondo  1894x718', null=True, upload_to='slider/'),
        ),
        migrations.AddField(
            model_name='edit_pag',
            name='img_vision',
            field=models.FileField(blank=True, help_text='fondo  1894x718', null=True, upload_to='slider/'),
        ),
        migrations.AddField(
            model_name='edit_pag',
            name='mision',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='edit_pag',
            name='vision',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
