# Generated by Django 4.0.6 on 2024-10-10 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biologico', '0022_edit_pag_about_sub_titulo1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='edit_pag',
            name='about_detalle1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
