# Generated by Django 4.0.6 on 2024-10-10 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biologico', '0023_edit_pag_about_detalle1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edit_pag',
            name='mision',
            field=models.TextField(blank=True, max_length=900, null=True),
        ),
        migrations.AlterField(
            model_name='edit_pag',
            name='vision',
            field=models.TextField(blank=True, max_length=900, null=True),
        ),
    ]
