# Generated by Django 4.0.6 on 2024-10-10 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biologico', '0025_edit_pag_about_destacado_01_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edit_pag',
            name='imag_fondo_02',
            field=models.FileField(blank=True, help_text='fondo   1894x718', null=True, upload_to='edit_web/'),
        ),
        migrations.AlterField(
            model_name='edit_pag',
            name='imag_fondo_03',
            field=models.FileField(blank=True, help_text='fondo  1894x718', null=True, upload_to='edit_web/'),
        ),
        migrations.AlterField(
            model_name='edit_pag',
            name='imag_fondo_04',
            field=models.FileField(blank=True, help_text='fondo  1894x718', null=True, upload_to='edit_web/'),
        ),
        migrations.AlterField(
            model_name='edit_pag',
            name='imag_fondo_05',
            field=models.FileField(blank=True, help_text='fondo  1894x718', null=True, upload_to='edit_web/'),
        ),
        migrations.AlterField(
            model_name='edit_pag',
            name='imag_fondo_06',
            field=models.FileField(blank=True, help_text='fondo  1894x718', null=True, upload_to='edit_web/'),
        ),
        migrations.AlterField(
            model_name='edit_pag',
            name='imag_pie',
            field=models.FileField(blank=True, help_text='fondo  1894x718', null=True, upload_to='edit_web/'),
        ),
        migrations.AlterField(
            model_name='edit_pag',
            name='img_mision',
            field=models.FileField(blank=True, help_text='fondo  1894x718', null=True, upload_to='edit_web/'),
        ),
        migrations.AlterField(
            model_name='edit_pag',
            name='img_vision',
            field=models.FileField(blank=True, help_text='fondo  1894x718', null=True, upload_to='edit_web/'),
        ),
    ]
