# Generated by Django 4.0.6 on 2024-10-10 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biologico', '0026_alter_edit_pag_imag_fondo_02_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='edit_pag',
            name='about_img01',
            field=models.FileField(blank=True, help_text='fondo  1894x718', null=True, upload_to='edit_web/'),
        ),
        migrations.AddField(
            model_name='edit_pag',
            name='about_img02',
            field=models.FileField(blank=True, help_text='fondo  1894x718', null=True, upload_to='edit_web/'),
        ),
    ]
