# Generated by Django 4.0.6 on 2024-10-20 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Biologico', '0027_edit_pag_about_img01_edit_pag_about_img02'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='antecedentes',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='litros_1',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='litros_20',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='litros_200',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='litros_4',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='utilizacion',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.CreateModel(
            name='Aplica_dosis_producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_foto', models.FileField(blank=True, help_text='slider  1600x964', null=True, upload_to='producto/')),
                ('titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('detalle', models.TextField(blank=True, max_length=400, null=True)),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Biologico.producto')),
            ],
            options={
                'verbose_name_plural': '4. Aplicación y dosis Productos ',
            },
        ),
    ]
