# Generated by Django 4.0.6 on 2024-10-20 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biologico', '0028_producto_antecedentes_producto_litros_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aplica_dosis_producto',
            old_name='detalle',
            new_name='aplicacion',
        ),
        migrations.RenameField(
            model_name='aplica_dosis_producto',
            old_name='titulo',
            new_name='cultivo',
        ),
        migrations.AddField(
            model_name='aplica_dosis_producto',
            name='dosis',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
