# Generated by Django 4.0.6 on 2024-10-22 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biologico', '0029_rename_detalle_aplica_dosis_producto_aplicacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='ficha_tecnica',
            field=models.FileField(blank=True, help_text='slider  1600x964', null=True, upload_to='producto/'),
        ),
    ]
