# Generated by Django 4.0.6 on 2024-11-05 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biologico', '0030_producto_ficha_tecnica'),
    ]

    operations = [
        migrations.AddField(
            model_name='marca',
            name='mapa',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
    ]
