# Generated by Django 4.0.6 on 2024-11-05 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biologico', '0031_marca_mapa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aplica_dosis_producto',
            name='img_foto',
        ),
        migrations.AddField(
            model_name='aplica_dosis_producto',
            name='icono',
            field=models.FileField(blank=True, help_text='icono  ', null=True, upload_to='producto/'),
        ),
    ]
