# Generated by Django 4.0.6 on 2024-11-12 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biologico', '0033_rename_logo_blanco_marca_logo_cuadrado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='detalle',
            field=models.TextField(blank=True, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='titulo',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
