# Generated by Django 4.0.6 on 2024-11-12 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biologico', '0034_alter_blog_detalle_alter_blog_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marca',
            name='facebook',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='marca',
            name='instagram',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='marca',
            name='tiktok',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='marca',
            name='youtube',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
