# Generated by Django 4.0.6 on 2024-12-04 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biologico', '0036_remove_marca_mision_remove_marca_vision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='logo_certificacion',
            field=models.FileField(blank=True, help_text='imagen certificacion', null=True, upload_to='producto/'),
        ),
        migrations.AddField(
            model_name='producto',
            name='logo_registro',
            field=models.FileField(blank=True, help_text='imagen registro', null=True, upload_to='producto/'),
        ),
    ]
