# Generated by Django 4.0.6 on 2024-12-04 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biologico', '0037_producto_logo_certificacion_producto_logo_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='nombre_certificacion',
            field=models.CharField(blank=True, help_text='Nombre de certificacion', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='nombre_registro',
            field=models.CharField(blank=True, help_text='Nombre de registro', max_length=200, null=True),
        ),
    ]
