# Generated by Django 4.0.6 on 2024-12-14 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biologico', '0038_producto_nombre_certificacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=90, null=True)),
                ('sub_titulo_1', models.CharField(blank=True, max_length=90, null=True)),
                ('sub_titulo_2', models.CharField(blank=True, max_length=90, null=True)),
                ('parrafo_1', models.TextField(blank=True, max_length=1000, null=True)),
                ('parrafo_2', models.TextField(blank=True, max_length=1000, null=True)),
                ('img_servicio_1', models.FileField(blank=True, help_text='imagen servicio', null=True, upload_to='servicio/')),
                ('img_servicio_2', models.FileField(blank=True, help_text='imagen servicio', null=True, upload_to='servicio/')),
                ('link_video_servicio', models.CharField(blank=True, help_text='Link youtube', max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': '4. Servicios ',
            },
        ),
    ]
