# Generated by Django 4.0.6 on 2024-12-14 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biologico', '0039_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='beneficio_1',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='beneficio_2',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='beneficio_3',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='beneficio_4',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
    ]
