# Generated by Django 4.0.6 on 2024-12-15 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biologico', '0040_servicio_beneficio_1_servicio_beneficio_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='beneficio_parrafo',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
