# Generated by Django 4.0.6 on 2024-12-15 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biologico', '0041_servicio_beneficio_parrafo'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='color',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
    ]
