# Generated by Django 4.0.6 on 2024-12-15 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biologico', '0042_servicio_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='orden',
            field=models.DecimalField(decimal_places=0, default=0.0, max_digits=2),
        ),
    ]
