# Generated by Django 4.0.6 on 2024-12-17 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biologico', '0043_slider_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='beneficio_5',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='beneficio_6',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
    ]
